### ISSUE TITLE
عدم دریافت پیامک

### ISSUE THREAD

**Issue by nimakh3** [behroozbc/kdz-portal#34]
فراموشیو میزنی کد ملی و شماره تماس میخوایم اس ام اس دریافت نمیکنیم

**Comment by behroozbc** [comment]
مربوط به پنل اس ام اس نیستش؟؟

**Comment by nimakh3** [comment]
این هنوز باگه نمیدونم والا
منم تست کردم ولی اس نمیده بهم

**Comment by behroozbc** [comment]
مراحلی که رفته رو ببین درست میگم 
۱. وارد سایت شدی
۲. دکمه فراموشی رو زدی
۳. شماره موبایل ات رو وارد کردی
۴. کد ملی هم همینطور وارد کردی
۵. دکمه ثبت رو زدی
۶. دکمه ثبت چرخیده 
۷. رفته مرحله بعد 
۸. منتظر اس ام اس بودی
مراحل اینا بوده؟؟

**Comment by nimakh3** [comment]
آره

**Comment by nimakh3** [comment]
اینم اوکی شد

**Comment by behroozbc** [comment]
حله
اگر میدونی اوکیه ببند

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
