### ISSUE TITLE
مشکل در فراموش رمز عبور

### ISSUE THREAD

**Issue by nimakh3** [behroozbc/kdz-portal#37]
در مرحله کد ملی درخواست کد دادیم موند وایساد زد شماره ۳ کلمه عبور و زدیم بروزرسانی موند در همین مرحله مراحلو انجام نمیدیم میریم مراحل بعدی میره

**Comment by behroozbc** [comment]
نمیدونم چیه ؟

**Comment by nimakh3** [comment]
این برای این بود که وقتی میاییم برای فراموشی رمز تهش که گزینه‌ی بروزرسانی داره اونجا بروزرسانی رو میزنه اتفاقی نمیوفته و نمیگه حله

**Comment by behroozbc** [comment]
فکر کنم دیشب این بخش کمی تغییر دادم یه تست کنید بهم بگید همون بوده یا نه

**Comment by nimakh3** [comment]
اوکیه برسم به آخرش میگم

**Comment by behroozbc** [comment]
منتظر ایشو #34 هستی؟

**Comment by nimakh3** [comment]
آره

**Comment by nimakh3** [comment]
اوکی شد بهروز

**Comment by behroozbc** [comment]
اگر اوکی شده ببند تازه برق گیر آوردم دارم کم کم آن میشم

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
