### ISSUE TITLE
دکمه بازگشت 

### ISSUE THREAD

**Issue by nimakh3** [behroozbc/kdz-portal#43]
یه دکمه‌ای بزار که تو مرحله‌های فراموشی رمز طرف بتونه برگرده
شاید یه دفعه رمزش یادش اومد خواست بره وارد کنه نمیخواد عوضش کنه
یا مثل من *** میخواد برگرده از اول باز مراخل رو پیش بره یه جا به باگ خورده

**Comment by behroozbc** [comment]
این رو اضافه کردم میتونی توی اینجا تست کنی https://behroozbc.github.io/kdz-portal/Authentication
